apiVersion: v1
kind: Service
metadata:
  name: collabvault-service # <srv-name>.<srv-namespace>.svc.cluster.local
spec:
  selector:
    app: web
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080