apiVersion: v1
kind: Service
metadata:
  name: collabvault-service
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080