# apiVersion: v1
# kind: Pod
# metadata:
#   name: collabvault-pod
#   labels:
#     app: web
# spec:
#   containers:
#     - name: my-container
#       image: simonebejko/collabvault:latest
#       env:
#         - name: PORT
#           value: "8080"
#         - name: WELCOME_MSG
#           valueFrom: 
#             configMapKeyRef:
#               name: collabvault-configmap
#               key: WELCOME_MSG
#       # envFrom:
#       #   - configMapRef:
#       #       name: django-configmap
#       envFrom:
#         - secretRef:
#             name: collabvault-secret
#       ports:
#         - containerPort: 8080